# Generated by Django 2.0.2 on 2018-02-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Person',
        ),
    ]
